# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='品牌名称')),
            ],
            options={
                'verbose_name': '品牌信息',
                'verbose_name_plural': '品牌信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='设备名称', max_length=32, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('品牌台式电脑', '品牌台式电脑'), ('笔记本电脑', '笔记本电脑'), ('组装台式机', '组装台式机')], help_text='设备类型', max_length=32, verbose_name='设备类型')),
                ('mainboard', models.CharField(blank=True, default='Intel', max_length=64, null=True, verbose_name='主板')),
                ('CPU', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=64, null=True, verbose_name='硬盘')),
                ('video', models.CharField(blank=True, choices=[('集成显卡', '集成显卡'), ('独立显卡', '独立显卡')], default='集成显卡', max_length=64, null=True, verbose_name='显卡')),
                ('displayer', models.CharField(blank=True, default='14英寸', max_length=64, null=True, verbose_name='显示器')),
            ],
            options={
                'verbose_name': '配置详情',
                'verbose_name_plural': '配置详情',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='物品编号')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='商品名称')),
                ('materialImg', models.ImageField(default='Material/default.png', null=True, upload_to='Material/%Y%m', verbose_name='物品图片')),
                ('spec', models.CharField(blank=True, max_length=120, null=True, verbose_name='规格/型号')),
                ('stock_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='单价')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Brand', verbose_name='品牌')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Category', verbose_name='物品分类')),
            ],
            options={
                'verbose_name_plural': '物品信息',
                'ordering': ['-id'],
                'verbose_name': '物品信息',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '单位类型',
                'verbose_name_plural': '单位类型',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='供应商名称')),
                ('type', models.CharField(choices=[('gt', '个体经营'), ('hlw', '互联网')], max_length=20, verbose_name='供应商类型')),
                ('phone', models.CharField(blank=True, default='88888888', max_length=13, null=True, verbose_name='联系电话')),
                ('addr', models.CharField(default='上海', max_length=24, null=True, verbose_name='地址')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('note', models.TextField(default=None, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.DateField(auto_created=datetime.datetime.now, verbose_name='创建时间')),
                ('p_id', models.CharField(max_length=32, unique=True, verbose_name='资产ID')),
                ('p_name', models.CharField(max_length=32, verbose_name='资产名称')),
                ('p_sn', models.CharField(max_length=32, unique=True, verbose_name='资产SN(序列号)')),
                ('p_price', models.IntegerField(verbose_name='资产金额')),
                ('p_image', models.ImageField(default='image/default.png', upload_to='property/%Y-%m-%d', verbose_name='资产图片')),
                ('p_status', models.CharField(choices=[('在用', '在用'), ('未用', '未用'), ('报废', '报废')], default='未用', max_length=32, verbose_name='资产状态')),
                ('p_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Brand', verbose_name='资产品牌')),
                ('p_computers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Computer', verbose_name='资产详情')),
                ('p_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Organization', verbose_name='供应商')),
            ],
            options={
                'verbose_name_plural': '资产详情',
                'ordering': ['-p_id'],
                'verbose_name': '资产详情',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='员工姓名')),
                ('dept', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='仓库编号')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='仓库名称')),
                ('location', models.CharField(max_length=120, verbose_name='位置')),
                ('users', models.ManyToManyField(blank=True, to='basedata.UserInfo', verbose_name='仓库管理员')),
            ],
            options={
                'verbose_name': '仓库信息',
                'verbose_name_plural': '仓库信息',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='p_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.UserInfo', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.UserInfo', verbose_name='所属人'),
        ),
        migrations.AddField(
            model_name='material',
            name='measures',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='物品单位'),
        ),
        migrations.AddField(
            model_name='material',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Warehouse', verbose_name='所属仓库'),
        ),
    ]
