# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-27 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='p_endtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='领取时间'),
            preserve_default=False,
        ),
    ]
