# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_property_p_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_endtime',
            field=models.DateTimeField(auto_now=True, verbose_name='领取时间'),
        ),
    ]
