# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-28 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_auto_20190927_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type',
            field=models.CharField(choices=[('品牌台式电脑', '品牌台式电脑'), ('笔记本电脑', '笔记本电脑'), ('组装台式机', '组装台式机'), ('打印机', '打印机'), ('投影仪', '投影仪')], help_text='设备类型', max_length=32, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video',
            field=models.CharField(blank=True, choices=[('集成显卡', '集成显卡'), ('独立显卡', '独立显卡'), ('无', '无')], default='集成显卡', max_length=64, null=True, verbose_name='显卡'),
        ),
    ]
