# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_auto_20190929_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.UserInfo', to_field='name', verbose_name='员工'),
        ),
    ]
