# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoFei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_time', models.DateField(default=django.utils.timezone.now, verbose_name='登记日期')),
                ('b_way', models.TextField(choices=[('zrsh', '自然损坏'), ('fzcsh', '非自然损坏'), ('ywxq', '满足不了业务需求'), ('nx', '超过使用年限'), ('qt', '其他原因')], default=None, verbose_name='报废原因')),
                ('b_num', models.IntegerField(default=1, verbose_name='数量')),
                ('b_note', models.CharField(default='空', max_length=200, verbose_name='备注')),
                ('b_ids', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Property', to_field='p_id', verbose_name='设备详情')),
                ('b_userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.UserInfo', verbose_name='申请人')),
            ],
            options={
                'verbose_name': '设备报废',
                'verbose_name_plural': '设备报废',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_company', models.CharField(choices=[('上海泰坦科技股份有限公司', '上海泰坦科技股份有限公司'), ('上海蒂剀姆溶剂有限公司', '上海蒂剀姆溶剂有限公司')], default='上海泰坦科技股份有限公司', max_length=32, verbose_name='公司名称')),
                ('c_time', models.DateField(auto_now=True, verbose_name='验收日期')),
                ('c_num', models.IntegerField(default=1, verbose_name='数量')),
                ('c_caigou_name', models.CharField(choices=[('王佳', '王佳'), ('胡兵', '胡兵')], default='王佳', max_length=32, verbose_name='采购负责人')),
                ('c_ghs_id', models.CharField(max_length=32, verbose_name='订单编号')),
                ('c_ysbg_wg', models.BooleanField(default=True, verbose_name='外观检查')),
                ('c_ysbg_jl', models.BooleanField(default=True, verbose_name='验收结论')),
                ('c_ysr_name', models.CharField(default='胡兵', max_length=32, verbose_name='验收人')),
                ('c_property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.Property', to_field='p_id', verbose_name='设备详情')),
            ],
            options={
                'verbose_name': '设备验收',
                'verbose_name_plural': '设备验收',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('type', models.CharField(choices=[('升级设备', '升级设备'), ('维修设备', '维修设备')], max_length=32, verbose_name='类型')),
                ('model_name', models.CharField(max_length=12, verbose_name='设备配件')),
                ('model_num', models.IntegerField(default=1, verbose_name='数量')),
                ('model_price', models.IntegerField(default=0, verbose_name='金额')),
                ('model_username', models.CharField(choices=[('胡兵', '胡兵'), ('杨学铭', '杨学铭')], max_length=32, verbose_name='维修负责人')),
                ('note', models.CharField(default='无', max_length=200, verbose_name='备注')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='单位')),
                ('propertys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Property', verbose_name='设备编号')),
            ],
            options={
                'verbose_name_plural': '设备升级',
                'ordering': ['-id'],
                'verbose_name': '设备升级',
            },
        ),
        migrations.CreateModel(
            name='FixedAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_time', models.DateField(auto_now=True, verbose_name='发放日期')),
                ('f_addr', models.CharField(max_length=32, verbose_name='归属城市')),
                ('f_note', models.CharField(max_length=200, verbose_name='备注')),
                ('f_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Property', verbose_name='设备详情')),
            ],
            options={
                'verbose_name_plural': '固定资产',
                'ordering': ['id'],
                'verbose_name': '固定资产',
            },
        ),
    ]
