# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-28 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itcomputer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baofei',
            name='b_way',
            field=models.CharField(choices=[('自然损坏', '自然损坏'), ('非自然损坏', '非自然损坏'), ('满足不了业务需求', '满足不了业务需求'), ('超过使用年限', '超过使用年限'), ('其他原因', '其他原因')], default=None, max_length=10, verbose_name='报废原因'),
        ),
    ]
