# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itcomputer', '0002_auto_20190928_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='propertys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Property', to_field='p_id', verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='f_time',
            field=models.DateField(auto_created=django.utils.timezone.now, verbose_name='发放日期'),
        ),
    ]
