# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itcomputer', '0003_auto_20190929_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model_username',
            field=models.CharField(choices=[('胡兵', '胡兵'), ('杨学铭', '杨学铭')], default='胡兵', max_length=32, verbose_name='维修负责人'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('升级设备', '升级设备'), ('维修设备', '维修设备')], default='升级设备', max_length=32, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='fixedassets',
            name='f_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Property', to_field='p_id', verbose_name='设备详情'),
        ),
    ]
