# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('note', models.TextField(default=None, verbose_name='问题描述')),
                ('status', models.BooleanField(default=True, verbose_name='完成状态')),
                ('jobuser', models.CharField(choices=[('hub', '胡兵'), ('admin', '管理员')], default='胡兵', max_length=32, verbose_name='维修人')),
                ('timeEnd', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '日常工作',
                'ordering': ['-id'],
                'verbose_name': '日常工作',
            },
        ),
        migrations.CreateModel(
            name='TypeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='问题类型')),
            ],
            options={
                'verbose_name': '问题类型',
                'verbose_name_plural': '问题类型',
            },
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='typejobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.TypeJob', to_field='name', verbose_name='问题类型'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basedata.UserInfo', to_field='name', verbose_name='提交人'),
        ),
    ]
