# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(auto_created=django.utils.timezone.now, verbose_name='采购日期')),
                ('crente_time', models.DateField(auto_created=django.utils.timezone.now, verbose_name='申请日期')),
                ('name', models.CharField(max_length=128, verbose_name='采购名称')),
                ('type', models.CharField(choices=[('京东', '京东'), ('淘宝', '淘宝')], default='淘宝', max_length=32, verbose_name='采购来源')),
                ('name_id', models.CharField(max_length=128, verbose_name='快递单号')),
                ('status', models.BooleanField(default=False, verbose_name='是否签收')),
                ('note', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '物流信息表',
                'verbose_name': '物流信息表',
            },
        ),
    ]
