# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworks',
            name='wuliu_name',
            field=models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], default='', max_length=32, verbose_name='物流公司'),
        ),
        migrations.AlterField(
            model_name='jobworks',
            name='note',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
    ]
