# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-29 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190928_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobworks',
            name='note',
            field=models.TextField(default='←详情请点单号', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='jobworks',
            name='wuliu_name',
            field=models.CharField(choices=[('中国邮政', '中国邮政'), ('申通快递', '申通快递'), ('圆通快递', '圆通快递'), ('顺丰快递', '顺丰快递'), ('天天快递', '天天快递'), ('韵达快递', '韵达快递'), ('中通快递', '中通快递'), ('汇通快递', '汇通快递')], default='', max_length=32, verbose_name='物流公司'),
        ),
    ]
