# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='设备名称')),
            ],
            options={
                'verbose_name': '设备名称',
                'verbose_name_plural': '设备名称',
            },
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='耗材名称')),
            ],
            options={
                'verbose_name': '耗材名称',
                'verbose_name_plural': '耗材名称',
            },
        ),
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_times', models.DateField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('num', models.IntegerField(default=1, verbose_name='申请数量')),
                ('addr', models.CharField(default='松江', max_length=32, verbose_name='所在地区')),
                ('note', models.CharField(default='无', max_length=255, verbose_name='备注')),
                ('model_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prints.ModelName', to_field='name', verbose_name='设备名称')),
                ('model_name_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prints.ModelType', to_field='name', verbose_name='耗材名称')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.UserInfo', to_field='name', verbose_name='申请人')),
            ],
            options={
                'verbose_name': '打印耗材',
                'verbose_name_plural': '打印耗材',
            },
        ),
    ]
