# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='库存数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Material', verbose_name='物品信息')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Measure', verbose_name='单位')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Organization', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.Warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '库存信息',
                'verbose_name_plural': '库存信息',
            },
        ),
    ]
